services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./volumes/jupyter:/home/jovyan/work
    networks:
      - data-science-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_science
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - data-science-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: data_science
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: password
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      - data-science-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - data-science-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472" # Usuário padrão do Grafana
    ports:
      - "3001:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - data-science-network

networks:
  data-science-network:
    driver: bridge
